const productTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  CART_TOTAL: "CART_TOTAL",
  SET_CONTACT_DETAILS: "SET_CONTACT_DETAILS",
  CLEAR_ALL: "CLEAR_ALL",
};
export default productTypes;
